### ISSUE TITLE
Error building theme

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.theme#110]
I've just checked out a fresh copy of ploneintranet.theme and followed the instructions on the README, in preparation for the Munich sprint next week.

After installing dependencies, running 'make' exists with the following error:

```
...
Your bundle is complete!
It was installed into ./.bundle/gemfiles
cd prototype && bundle exec jekyll build
Configuration file: /home/zope/ploneintranet.theme/prototype/_config.yml
            Source: /home/zope/ploneintranet.theme/prototype
       Destination: /home/zope/ploneintranet.theme/prototype/_site
      Generating...
DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: &.undecided

                    done.
 Auto-regeneration: disabled. Use --watch to enable.
node_modules/.bin/r.js -o build.js optimize=none

Tracing dependencies for: almond
Error: ENOENT, no such file or directory '/home/zope/ploneintranet.theme/src/mockup-patterns-base.js'
In module tree:
    patterns
      pat-upload

Error: Error: ENOENT, no such file or directory '/home/zope/ploneintranet.theme/src/mockup-patterns-base.js'
In module tree:
    patterns
      pat-upload

    at Object.fs.openSync (fs.js:438:18)

make: *** [bundle.js] Error 1
```

Chatting to @adrianwhite, he is seeing the same issues and thinks it may be related to the new aloha pattern. @jcbrand is this something you are aware of?

**Comment by pilz** [comment]
Quick shot. @mattss  @adrianwhite Can you try to add these lines to your build.js?

"mockup-parser":        "bower_components/mockup-core/js/parser",$
"mockup-patterns-base": "bower_components/mockup-core/js/pattern",$

**Comment by jcbrand** [comment]
@pilz, @mattss: Yes, that should do it.

**Comment by mattss** [comment]
New error:

```
Tracing dependencies for: almond
Error: ENOENT, no such file or directory '/home/zope/ploneintranet.theme/src/i18n.js'
In module tree:
    patterns
      pat-upload

Error: Error: ENOENT, no such file or directory '/home/zope/ploneintranet.theme/src/i18n.js'
In module tree:
    patterns
      pat-upload

    at Object.fs.openSync (fs.js:438:18)

make: *** [bundle.js] Error 1
```

**Comment by pilz** [comment]
I have this line to offer:
"i18n":                 "bower_components/patternslib/src/core/i18n",

**Comment by mattss** [comment]
That works - I've just added a PR with the changes.
